# Backup Configuration

# Source and target locations
source: "/Volumes/Backup Vol 1/Family_Media_backup"
target: "/Volumes/Backup Vol 2/Family_Media_backup"

# Directories to include (relative to source)
# Only these directories will be backed up
# If empty, all directories will be backed up
include_dirs:
  - "Books"
  - "Desktop"
  - "Home Movies"
  - "Photos"
  - "Pictures"

# Files or patterns to exclude
exclude_patterns:
  - ".DS_Store"
  - ".Spotlight-V100"
  - ".Trashes"
  - ".fseventsd"
  - "._*"
  - "*.tmp"
  - "Thumbs.db"

# Log directory (optional, defaults to $HOME/backup-logs)
log_dir: "$HOME/backup-logs"